name: Update RSS

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: "0 8 * * *"

jobs:
  update_rss_feeds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: Install dependencies
        run: go install cmd/gohumble.go
      - name: Run gohumble
        run: cd docs && gohumble
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
